### ISSUE TITLE
Use new dashboard API

### ISSUE THREAD

**Issue by nitroin** [cycle2work/c2w-site-front#11]
This [PR](https://github.com/cycle2work/c2w-lambda-api-dashboard/pull/7) opens for greater flexibility for data visualization by moving the filtering and reduce to the frontend.

This require some changes in data fetching and manipulation for the dashboard page:

#### Tasks:

- [ ] Remove `reports` fetch from dashboard page.
- [ ] Fetch data one time only
- [ ] Remove canned data for `clubId`
- [ ] Update personal today stats
- [ ] Update personal monthly data
- [ ] Update club stats
